CC:=g++

sourcedir:=source
headerdir:=header
objectdir:=object
dependdir:=depend
binarydir:=binary
exportdir:=export

debugdir:=debug
releasedir:=release
defaultdir:=

sourceextension:=.cc
includedirs:=$(headerdir) catch/include

# -s flag strips symbols
# not doing this allows a 'client' to run a `gdb main` `bt`
#   which could be useful
defaultflags:= -Wall -Wextra -pedantic -std=c++14
# -O2 flag might break things..
releaseflags:= $(defaultflags) -s
debugflags:= $(defaultflags) -DDEBUG -ggdb3

name:=main

builds:=default debug release

all:debug release

export: release
	mkdir $(exportdir)
	ar -cvq export/libArgParse.a object/release/argparse.o

#TODO:investigate using -fbranch-probabilities
#website appears to be a useful resource:
#  alex.dzyoba.com/linux/profiling-gprof-gcov.html

